### ISSUE TITLE
Enter email -> click Save should save the email

### ISSUE THREAD

**Issue by dmurko** [niteoweb/passive-indexation-check#3]
Right now you need to add email, click plus button, then click Save. It's more intuitive to click Save when you add the email and use plus only when adding additional emails in the same step.

**Comment by ZeroCool51** [comment]
If the email is invalid, do the settings update anyway? Or does the whole form need to be correct?

**Comment by ZeroCool51** [comment]
It is prompted to enter a correct email address if anything is entered in the email address while updating settings.

Waiting for merge request to be completed.
